return {
	-- armas CaC simples -----------------------------------------------
	adaga = {
		nome = "Adaga",
		empunhadura = "uma_mao",
		tipo = "corpo simples",
		proficiencia = 3,
		dano = "1d4",
		alcance = "5/10",
		grupo = "leve",
		mao_inabil = true,
		leve_arremesso = true,
	},
	azagaia = {
		nome = "Azagaia",
		empunhadura = "uma_mao",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "1d6",
		alcance = "10/20",
		grupo = "lanca",
		pesada_arremesso = true,
	},
	clava = {
		nome = "Clava",
		empunhadura = "uma_mao",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "1d6",
		grupo = "maca",
	},
	foice = {
		nome = "Foice",
		empunhadura = "uma_mao",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "1d6",
		grupo = "leve",
		mao_inabil = true,
	},
	lanca_curta = {
		nome = "Lança Curta",
		empunhadura = "uma_mao",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "1d8",
		grupo = "lanca",
		versatil = true,
	},
	maca = {
		nome = "Maça",
		empunhadura = "uma_mao",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "1d8",
		grupo = "maca",
		versatil = true,
	},
	bordao = {
		nome = "Bordão",
		empunhadura = "duas_maos",
		tipo = "corpo simples",
		proficiencia = 2,
		tipo = "corpo simples",
		dano = "1d8",
		grupo = "bordao",
	},
	clava_grande = {
		nome = "Clava Grande",
		empunhadura = "duas_maos",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "2d4",
		grupo = "maca",
	},
	maca_estrela = {
		nome = "Maça Estrela",
		empunhadura = "duas_maos",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "1d10",
		grupo = "maca",
	},
	segadeira = {
		nome = "Segadeira",
		empunhadura = "duas_maos",
		tipo = "corpo simples",
		proficiencia = 2,
		dano = "2d4",
		grupo = "pesada",
	},
	-- armas CaC militares ----------------------------------------------
	cimitarra = {
		nome = "Cimitarra",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d8",
		grupo = "pesada",
		decisivo_elevado = true,
	},
	espada_curta = {
		nome = "Espada Curta",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 3,
		dano = "1d6",
		grupo = "leve",
		mao_inabil = true,
	},
	espada_longa = {
		nome = "Espada Longa",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 3,
		dano = "1d8",
		grupo = "pesada",
		versatil = true,
	},
	espada_larga = {
		nome = "Espada Larga",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d10",
		grupo = "pesada",
		versatil = true,
	},
	machadinha = {
		nome = "Machadinha",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d6",
		alcance = "5/10",
		grupo = "machado",
		mao_inabil = true,
		pesada_arremesso = true,
	},
	machado_batalha = {
		nome = "Machado de Batalha",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d10",
		grupo = "machado",
		versatil = true,
	},
	mangual = {
		nome = "Mangual",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d10",
		grupo = "mangual",
		versatil = true,
	},
	martelo_de_arremesso = {
		nome = "Martelo de Arremesso",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d6",
		alcance = "5/10",
		grupo = "martelo",
		mao_inabil = true,
		pesada_arremesso = true,
	},
	martelo_de_guerra = {
		nome = "Martelo de Guerra",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d10",
		grupo = "martelo",
		versatil = true,
	},
	picareta_guerra = {
		nome = "Picareta de Guerra",
		empunhadura = "uma_mao",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d8",
		grupo = "picareta",
		decisivo_elevado = true,
		versatil = true,
	},
	alabarda = {
		nome = "Alabarda",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d10",
		grupo = "machado", -- haste
		de_alcance = true,
	},
	alfange = {
		nome = "Alfange",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 3,
		dano = "2d4",
		grupo = "pesada",
		decisivo_elevado = true,
	},
	espada_grande = {
		nome = "Espada Grande",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 3,
		dano = "1d10",
		grupo = "pesada",
	},
	glaive = {
		nome = "Glaive",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "2d4",
		grupo = "pesada", -- haste
		de_alcance = true,
	},
	lanca_longa = {
		nome = "Lança Longa",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d10",
		grupo = "haste", -- lanca
		de_alcance = true,
	},
	machado_grande = {
		nome = "Machado Grande",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "1d12",
		grupo = "machado",
		decisivo_elevado = true,
	},
	malho = {
		nome = "Malho",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "2d6",
		grupo = "martelo",
	},
	mangual_pesado = {
		nome = "Mangual Pesado",
		empunhadura = "duas_maos",
		tipo = "corpo militar",
		proficiencia = 2,
		dano = "2d6",
		grupo = "mangual",
	},
	-- armas CaC superiores ---------------------------------------------
	montante = {
		nome = "Montante",
		empunhadura = "duas_maos",
		tipo = "corpo superior",
		proficiencia = 3,
		dano = "1d12",
		grupo = "pesada",
		decisivo_elevado = true,
	},
	espada_bastarda = {
		nome = "Espada Bastarda",
		empunhadura = "uma_mao",
		tipo = "corpo superior",
		proficiencia = 3,
		dano = "1d10",
		grupo = "pesada",
		versatil = true,
	},
	katar = {
		nome = "Katar",
		empunhadura = "uma_mao",
		tipo = "corpo superior",
		proficiencia = 3,
		dano = "1d6",
		grupo = "leve",
		decisivo_elevado = true,
		mao_inabil = true,
	},
	rapieira = {
		nome = "Rapieira",
		empunhadura = "uma_mao",
		tipo = "corpo superior",
		proficiencia = 3,
		dano = "1d8",
		grupo = "leve",
	},
	sabre = {
		nome = "Sabre",
		empunhadura = "uma_mao",
		tipo = "corpo superior",
		proficiencia = 3,
		dano = "1d8",
		grupo = "leve",
		decisivo_elevado = true,
	},
	corrente_com_cravos = {
		nome = "Corrente com Cravos",
		empunhadura = "duas_maos",
		tipo = "corpo superior",
		proficiencia = 3,
		dano = "2d4",
		grupo = "mangual",
		de_alcance = true,
	},
	-- armas distância simples -----------------------------------------
	besta_mao = {
		nome = "Besta de Mão",
		empunhadura = "uma_mao",
		tipo = "distancia simples",
		proficiencia = 2,
		dano = "1d6",
		alcance = "10/20",
		grupo = "besta",
		recarga_livre = true,
	},
	funda = {
		nome = "Funda",
		empunhadura = "uma_mao",
		tipo = "distancia simples",
		proficiencia = 2,
		dano = "1d6",
		alcance = "10/20",
		grupo = "atiradeira",
		recarga_livre = true,
	},
	besta = {
		nome = "Besta",
		empunhadura = "duas_maos",
		tipo = "distancia simples",
		proficiencia = 2,
		dano = "1d8",
		alcance = "15/30",
		grupo = "besta",
		recarga_minima = true,
	},
	-- armas distância militares ---------------------------------------
	arco_curto = {
		nome = "Arco Curto",
		empunhadura = "duas_maos",
		tipo = "distancia militar",
		proficiencia = 2,
		dano = "1d8",
		alcance = "15/30",
		grupo = "arco",
		pequena = true,
		recarga_livre = true,
	},
	arco_longo = {
		nome = "Arco Longo",
		empunhadura = "duas_maos",
		tipo = "distancia militar",
		proficiencia = 2,
		dano = "1d10",
		alcance = "20/40",
		grupo = "arco",
		recarga_livre = true,
	},
	-- armas distância superiores --------------------------------------
	arco_grande = {
		nome = "Arco Grande",
		empunhadura = "duas_maos",
		tipo = "distancia superior",
		proficiencia = 2,
		dano = "1d12",
		alcance = "25/50",
		grupo = "arco",
		recarga_livre = true,
	},
	shuriken = {
		nome = "Shuriken",
		empunhadura = "uma_mao",
		tipo = "distancia superior",
		proficiencia = 3,
		dano = "1d4",
		alcance = "6/12",
		grupo = "leve",
		leve_arremesso = true,
	},

	manopla_shuriken = {
		nome = "Manopla de Shuriken",
		empunhadura = "uma_mao",
		tipo = "distancia militar",
		proficiencia = 3,
		dano = "1d8",
		alcance = "8/16",
		grupo = "leve",
		leve_arremesso = true,
	},
}
