local set = require"Set"
local soma_dano = require"Soma".soma
local armas = require"Armas"
local tipos_armas = require"TiposArmas"

local categorias_dano = {
	uma_mao = {
		["1d4"] = "1d6",
		["1d6"] = "1d8",
		["1d8"] = "1d10",
		["1d10"] = "1d12",
		["1d12"] = "2d6",
		["2d6"] = "2d8",
		["2d8"] = "2d10",
	},
	duas_maos = {
		["1d8"] = "2d4",
		["2d4"] = "1d10",
		["1d10"] = "1d12",
		["1d12"] = "2d6",
		["2d6"] = "2d8",
		["2d8"] = "2d10",
	},
}

return {
	["Bárbaro"] = {
		nome = "Bárbaro",
		Fortitude = 2,
		armaduras = set("traje", "corselete", "gibao"),
		armas = tipos_armas("corpo simples", "corpo militar"),
		PV = 15,
		PV_Nivel = 6,
		PC_Dia = 8,
		pericias = set("acrobacia", "atletismo", "intimidacao", "natureza", "percepcao", "socorro", "tolerancia"),
		total_pericias = 3,
	},
	["Bardo"] = {
		nome = "Bardo",
		Reflexos = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete", "gibao", "cota", "leve"),
		armas = tipos_armas("corpo simples", "distancia simples", "distancia militar", "cimitarra", "espada_curta", "espada_longa"),
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 7,
		pericias = {
			arcanismo = "treinada",
			acrobacia = true,
			atletismo = true,
			blefe = true,
			diplomacia = true,
			exploracao = true,
			historia = true,
			intimidacao = true,
			intuicao = true,
			manha = true,
			natureza = true,
			percepcao = true,
			religiao = true,
			socorro = true,
		},
		total_pericias = 4,
	},
	["Bruxo"] = {
		nome = "Bruxo",
		Reflexos = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete"),
		armas = tipos_armas("corpo simples", "distancia simples"),
		implementos = set("orbe", "varinha"),
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 6,
		pericias = set("arcanismo", "blefe", "historia", "intimidacao", "intuicao", "ladinagem", "manha", "religiao"),
		total_pericias = 4,
	},
	["Clérigo"] = {
		nome = "Clérigo",
		Vontade = 2,
		armaduras = set("traje", "corselete", "gibao", "cota"),
		armas = tipos_armas("corpo simples", "distancia simples"),
		implementos = set("simbolo_sagrado"),
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 7,
		pericias = {
			religiao = "treinada",
			arcanismo = true,
			diplomacia = true,
			historia = true,
			intuicao = true,
			socorro = true,
		},
		total_pericias = 3,
	},
	["Druida"] = {
		nome = "Druida",
		Reflexos = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete", "gibao"),
		armas = tipos_armas("corpo simples", "distancia simples"),
		implementos = set("cajado", "totem"),
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 7,
		pericias = {
			natureza = "treinada",
			arcanismo = true,
			atletismo = true,
			diplomacia = true,
			historia = true,
			intuicao = true,
			percepcao = true,
			socorro = true,
			tolerancia = true,
		},
		total_pericias = 3,
	},
	["Feiticeiro"] = {
		nome = "Feiticeiro",
		Vontade = 2,
		armaduras = set("traje"),
		armas = tipos_armas("corpo simples", "distancia simples"),
		implementos = set("adaga", "cajado"),
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 6,
		pericias = {
			arcanismo = "treinada",
			atletismo = true,
			blefe = true,
			diplomacia = true,
			exploracao = true,
			historia = true,
			intimidacao = true,
			intuicao = true,
			natureza = true,
			tolerancia = true,
		},
		total_pericias = 3,
	},
	["Guardião"] = {
		nome = "Guardião",
		Fortitude = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete", "gibão", "leve", "pesado"),
		armas = tipos_armas("corpo simples", "corpo militar", "distancia simples"),
		PV = 17,
		PV_Nivel = 7,
		PC_Dia = 9,
		pericias = {
			natureza = "treinada",
			atletismo = true,
			exploracao = true,
			intimidacao = true,
			natureza = true,
			percepcao = true,
			socorro = true,
			tolerancia = true,
		},
		total_pericias = 3,
	},
	["Guerreiro"] = {
		nome = "Guerreiro",
		Fortitude = 2,
		armaduras = set("traje", "corselete", "gibao", "cota", "brunea", "leve", "pesado"),
		armas = tipos_armas("corpo simples", "corpo militar", "distancia simples", "distancia militar"),
		implementos = {},
		ataque = function(self, arma)
			if arma.empunhadura == self.empunhadura then
				return 1
			else
				return 0
			end
		end,
		PV = 15,
		PV_Nivel = 6,
		PC_Dia = 9,
		pericias = set("atletismo", "intimidacao", "manha", "socorro", "tolerancia"),
		total_pericias = 3,
	},
	["Invocador"] = {
		nome = "Invocador",
		Fortitude = 1,
		Reflexos = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete", "gibão", "cota"),
		armas = tipos_armas("corpo simples", "distancia simples"),
		implementos = set("bastão", "cajado"),
		PV = 10,
		PV_Nivel = 4,
		PC_Dia = 6,
		pericias = {
			religiao = "treinada",
			arcanismo = true,
			diplomacia = true,
			historia = true,
			intimidacao = true,
			intuicao = true,
			tolerancia = true,
		},
		total_pericias = 3,
	},
	["Ladino"] = require"Ladino",
	["Mago"] = require"Mago",
	["Paladino"] = require"Paladino",
	["Patrulheiro"] = require"Patrulheiro",
	["Senhor da Guerra"] = {
		nome = "Senhor da Guerra",
		Fortitude = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete", "gibao", "cota", "leve", "pesado"),
		armas = tipos_armas("corpo simples", "corpo militar", "distancia simples"),
		implementos = {},
		iniciativa = 2,
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 7,
		pericias = set("atletismo", "diplomacia", "historia", "intimidacao", "socorro", "tolerancia"),
		total_pericias = 4,
	},
	["Vingador"] = {
		nome = "Vingador",
		CA = function(self)
			if self.armadura == "traje" then
				return 3
			end
		end,
		Fortitude = 1,
		Reflexos = 1,
		Vontade = 1,
		armaduras = set("traje"),
		armas = tipos_armas("corpo simples", "corpo militar", "distancia simples"),
		implementos = set("simbolo_sagrado"),
		PV = 14,
		PV_Nivel = 6,
		PC_Dia = 7,
		pericias = {
			religiao = "treinada",
			acrobacia = true,
			atletismo = true,
			furtividade = true,
			intimidacao = true,
			manha = true,
			percepcao = true,
			socorro = true,
			tolerancia = true,
		},
		total_pericias = 3,
	},
	["Xamã"] = {
		nome = "Xamã",
		Fortitude = 1,
		Vontade = 1,
		armaduras = set("traje", "corselete"),
		armas = tipos_armas("corpo simples", "lanca_longa"),
		implementos = set("totem"),
		PV = 12,
		PV_Nivel = 5,
		PC_Dia = 7,
		pericias = {
			natureza = "treinada",
			arcanismo = true,
			atletismo = true,
			historia = true,
			intuicao = true,
			percepcao = true,
			religiao = true,
			socorro = true,
			tolerancia = true,
		},
		total_pericias = 3,
	},

	companheiro = {
		ca = function(self)
			local ca = 14 + self.nivel
			self.ca_oportunidade = ca
			return ca
		end,
		fortitude = function(self)
			return 11+self.nivel
		end,
		reflexos = function(self)
			return 13+self.nivel
		end,
		vontade = function(self)
			return 12+self.nivel
		end,
		pc_dia = 2,
		pv = 14 - 12 + 8, -- PV básico - constituicao + pv_nivel
		pv_nivel = 8,
		total_pericias = 0,
		pericias = set("atletismo", "exploracao", "furtividade"),
		poderes = {},
	},
}
